spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bugtracker
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    cache: false
server:
  port: 8080